clip_norm:
  value: 5
data:
  batch_size: 1
  chunk_size: 32000
  data_root: F:/ISSAI_KSC2_unpacked/DIHARD_DATA_INFO/CONCATED_DFS_train_crowdsourced_tvnews_tts=5000_k=2.csv
  least_size: 16000
  num_workers: 0
  pin_memory: true
  sample_rate: 16000
  seed: 42
  shuffle: false
  test_percent: 0.1
  total_percent: 0.02
  train_percent: 0.8
  valid_percent: 0.1
model:
  K: 250
  bidirectional: true
  dropout: 0
  hidden_channels: 128
  in_channels: 256
  kernel_size: 2
  norm: ln
  num_layers: 6
  out_channels: 64
  rnn_type: LSTM
  speaker_num: 2
scheduler:
  factor: 0.5
  min_lr: 1.0e-08
  patience: 2
trainer:
  alpha: 0.55
  best_weights: false
  beta: 0.45
  checkpoint_interval: 1
  checkpointing: false
  ckpt_folder: ./checkpoints/
  device: cuda
  epochs: 900
  model_name: DualPath_RNN
  path_to_weights: ./weights/dev_dualpathrnn
  speaker_num: 2
  trained_model: ''
training:
  lr: 0.0005
  momentum: 0
  optim: Adam
  weight_decay: 0
xp_config:
  dataset: ISSAI_KSC2
  model_type: Separation
  speaker_num: 2
