clip_norm: 0
data:
  batch_size: 1
  chunk_size: 32000
  data_root: F:/ISSAI_KSC2_unpacked/DIHARD_DATA_INFO/CONCATED_DFS_train_crowdsourced_tvnews_tts=5000_k=2.csv
  least_size: 16000
  num_workers: 0
  pin_memory: true
  sample_rate: 16000
  seed: 42
  shuffle: false
  test_percent: 0.1
  total_percent: 1.0
  train_percent: 0.8
  valid_percent: 0.1
model:
  K: 250
  d_ff_inter: 1024
  d_ff_intra: 1024
  d_inter: 256
  d_intra: 256
  dropout: 0.0
  encoder_type_norm: ln
  kernel_size: 16
  num_heads_inter: 8
  num_heads_intra: 8
  num_layers: 2
  num_layers_inter: 8
  num_layers_intra: 8
  out_channels: 256
  speaker_num: 2
scheduler:
  factor: 0.5
  min_lr: 1.0e-08
  patience: 2
trainer:
  alpha: 0.55
  best_weights: true
  beta: 0.45
  checkpoint_interval: 1
  checkpointing: true
  ckpt_folder: ./checkpoints/
  device: cuda
  epochs: 900
  model_name: SuperiorSepformer
  path_to_weights: ./weights/superiorsepformer
  speaker_num: 2
  trained_model: ''
training:
  lr: 1.5
  optim: Adam
xp_config:
  dataset: ISSAI_KSC2
  model_type: Separation
  speaker_num: 2
