data:
  batch_size: 1
  chunk_size: 32000
  data_root: F:/ISSAI_KSC2_unpacked/DIHARD_DATA_INFO/CONCATED_DFS_tts=2000_k_2.csv
  least_size: 16000
  num_workers: 0
  pin_memory: true
  sample_rate: 16000
  seed: 42
  shuffle: true
  test_percent: 0.0
  train_percent: 0.8
  valid_percent: 0.2
datasets:
  batch_size: 1
  chunk_size: 32000
  least_size: 16000
  num_workers: 0
  pin_memory: true
  sample_rate: 16000
  seed: 42
  shuffle: true
  train_dataroot_mix: F:/ISSAI_KSC2_unpacked/diahard_data/scp_files_k=2/tr_mix.scp
  train_dataroot_target_s1: F:/ISSAI_KSC2_unpacked/diahard_data/scp_files_k=2/tr_s1.scp
  train_dataroot_target_s2: F:/ISSAI_KSC2_unpacked/diahard_data/scp_files_k=2/tr_s2.scp
  val_dataroot_mix: F:/ISSAI_KSC2_unpacked/diahard_data/scp_files_k=2/cv_mix.scp
  val_dataroot_target_s1: F:/ISSAI_KSC2_unpacked/diahard_data/scp_files_k=2/cv_s1.scp
  val_dataroot_target_s2: F:/ISSAI_KSC2_unpacked/diahard_data/scp_files_k=2/cv_s2.scp
model:
  K: 250
  bidirectional: true
  dropout: 0
  hidden_channels: 128
  in_channels: 256
  kernel_size: 2
  norm: ln
  num_layers: 6
  out_channels: 64
  rnn_type: LSTM
  speaker_num: 2
trainer:
  best_weights: false
  checkpoint_interval: 5
  checkpointing: false
  ckpt_folder: ./checkpoints/
  device: cuda
  model_name: Dual_Path_RNN
  num_epochs: 100
  path_to_weights: ./weights
  resume: false
  speaker_num: 2
training:
  clip_norm: 5
  lr: 0.01
  momentum: 0
  optim: Adam
  weight_decay: 1.0e-05
xp_config:
  dataset: ISSAI_KSC2
  model_type: Dual_Path_RNN
  speaker_num: 2
  use_tb_logger: false
