xp_config:
  model_type: Conv_TasNet
  dataset: ISSAI_KSC2
  use_tb_logger: false
  speaker_num: 2

data:
  data_root: 'F:/ISSAI_KSC2_unpacked/DIHARD_DATA_INFO/CONCATED_DFS_train_crowdsourced_tvnews_tts=5000_k=2.csv'
  total_percent: 1.0
  train_percent: 0.8
  valid_percent: 0.1
  test_percent: 0.1
  shuffle: false
  num_workers: 0 
  batch_size: 1
  pin_memory: true
  sample_rate: 16000
  chunk_size: 32000
  least_size: 16000
  seed: 42

model:
  N: 512
  L: 16
  B: 128
  H: 512
  P: 3
  X: 8
  R: 3
  norm: gln
  num_spks: 2
  activate: relu
  causal: false

trainer:
  epochs: 200
  device: 'cuda'
  best_weights: true
  checkpointing: true
  checkpoint_interval: 1
  model_name: Conv_TasNet
  trained_model: '' # weights/Dual_Path_RNN_1_-0.1336.pt 
  path_to_weights: './weights/conv_tasnet'
  ckpt_folder: ./checkpoints/
  speaker_num: 2
  alpha: 0.55
  beta: 0.45

training:
  optim: Adam   ### Adam, RMSprop, SGD
  lr: !!float 0.003
  weight_decay: 1.0e-05
  momentum: 0.9
  clip_norm: 200