xp_config:
  model_type: Separation
  dataset: ISSAI_KSC2
  speaker_num: 2

data:
  data_root: 'F:/ISSAI_KSC2_unpacked/DIHARD_DATA_INFO/CONCATED_DFS_train_crowdsourced_tvnews_tts=5000_k=2.csv'
  total_percent: 0.02
  train_percent: 0.8
  valid_percent: 0.1
  test_percent: 0.1
  shuffle: false
  num_workers: 0 
  batch_size: 1
  pin_memory: true
  sample_rate: 16000
  chunk_size: 32000
  least_size: 16000
  seed: 42

model: 
  out_channels: 512
  kernel_size: 8
  encoder_type_norm: 'ln'
  num_layers_intra: 8 
  num_layers_inter: 8
  num_heads_intra: 8
  num_heads_inter: 8
  d_intra: 512
  d_inter: 512
  d_ff_intra: 1024 
  d_ff_inter: 1024
  num_layers: 2
  dropout: 0.0
  K: 250 
  speaker_num: 2

trainer:
  epochs: 900
  device: 'cuda'
  best_weights: false
  checkpointing: false
  checkpoint_interval: 1
  model_name: 'SuperiorSepformer' # Right Sepformer
  trained_model: '' # checkpoints/sepformer/
  path_to_weights: './weights/superiorsepformer'
  ckpt_folder: ./checkpoints/
  speaker_num: 2
  alpha: 0.55
  beta: 0.45

training:
  optim: Adam   ### Adam, RMSprop, SGD
  lr: !!float 15.0e-5

clip_norm: 0

scheduler:
  min_lr: !!float 1e-8
  patience: 2
  factor: 0.5