data:
  batch_size: 1
  chunk_size: 32000
  data_root: F:/ISSAI_KSC2_unpacked/DIHARD_DATA_INFO/CONCATED_DFS_train_tts_tvnews=5000_k=2.csv
  least_size: 16000
  num_workers: 0
  pin_memory: true
  sample_rate: 16000
  seed: 42
  shuffle: false
  test_percent: 0.1
  total_percent: 1.0
  train_percent: 0.8
  valid_percent: 0.1
model:
  C: 2
  Global_B: 2
  H: 8
  K: 250
  L: 16
  Local_B: 8
  N: 256
trainer:
  best_weights: true
  checkpoint_interval: 1
  checkpointing: true
  ckpt_folder: ./checkpoints/
  device: cuda
  model_name: Sepformer
  num_epochs: 200
  path_to_weights: ./weights
  resume: false
  speaker_num: 2
  trained_model: ''
training:
  clip_norm: 5
  lr: 0.001
  momentum: 0
  optim: Adam
  weight_decay: 1.0e-05
xp_config:
  dataset: ISSAI_KSC2
  model_type: Sepformer
  speaker_num: 2
  use_tb_logger: false
